# Generated by Django 3.2.4 on 2021-07-29 22:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_hike_hikemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hikemodel',
            name='hike_location',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
