# Generated by Django 3.2.4 on 2021-07-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_hikemodel_hike_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='locationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50)),
            ],
        ),
    ]
