# Generated by Django 3.2.4 on 2021-07-29 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_locationmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='locationModel',
        ),
    ]
