# Generated by Django 3.2.4 on 2021-07-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_locationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50, verbose_name='Location Name')),
                ('location_description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='hikemodel',
            name='hike_difficulty',
            field=models.CharField(blank=True, default='hard', max_length=50),
        ),
        migrations.AlterField(
            model_name='hikemodel',
            name='hike_description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
