# Generated by Django 3.2.4 on 2021-07-29 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0006_hikemodel_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='HikeMeUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50, verbose_name='Location Name')),
                ('location_description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='hikemodel',
            name='hike_difficulty',
            field=models.CharField(default=1, max_length=10, verbose_name='Hike Difficulty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hikemodel',
            name='hike_status',
            field=models.CharField(default=1, max_length=6, verbose_name='Hike Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hikemodel',
            name='hike_description',
            field=models.TextField(blank=True, max_length=200, verbose_name='Hike Description'),
        ),
        migrations.AlterField(
            model_name='hikemodel',
            name='hike_name',
            field=models.CharField(max_length=50, verbose_name='Hike Name'),
        ),
        migrations.CreateModel(
            name='UserReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hikemodel',
            name='hike_hikers',
            field=models.ManyToManyField(blank=True, to='myapp.HikeMeUsers'),
        ),
        migrations.AlterField(
            model_name='hikemodel',
            name='hike_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.locations'),
        ),
    ]
