# Generated by Django 3.2.4 on 2021-07-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_hikemodel_hike_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='hikemodel',
            name='hike_location',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
