# Generated by Django 3.2.4 on 2021-07-29 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_hikemodel_hike_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hikemodel',
            name='hike_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.locations'),
        ),
    ]
