# Generated by Django 3.2.4 on 2021-07-30 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210729_2312'),
        ('myapp', '0012_alter_hikemodel_hike_description'),
    ]

    operations = [
    ]
