# Generated by Django 3.2.4 on 2021-07-31 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_merge_20210730_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hikemodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='hikemodel',
            name='hike_status',
        ),
        migrations.AlterField(
            model_name='hikemodel',
            name='hike_description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='hikemodel',
            name='hike_difficulty',
            field=models.CharField(blank=True, default='hard', max_length=50),
        ),
        migrations.AlterField(
            model_name='hikemodel',
            name='hike_name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='UserReply',
        ),
    ]
